name: MeteorAnarchy
version: @version@
main: minegame159.meteoranarchy.MeteorAnarchy
api-version: 1.16
authors: [MineGame159]
description: Plugin for our anarchy server

depend:
  - PlaceholderAPI
  - DeathMessagesPrime
  - Votifier
